### ISSUE TITLE
'502 Bad Gateway' is shown

### ISSUE THREAD

**Issue by kawarimidoll** [capjamesg/bsky.link#1]
Hi,
I tried to input this URL https://staging.bsky.app/profile/kawarimidoll.bsky.social/post/3jtvu75t32s2g , but '502 Bad Gateway' is shown, not my post.

![SCR-20230422-idjq](https://user-images.githubusercontent.com/8146876/233749492-479ca603-32e8-44ae-9a81-29939e6d6185.png)

**Comment by capjamesg** [comment]
Thank you for flagging! This has now been fixed.

Example URL: https://bsky.link/?url=https://staging.bsky.app/profile/kawarimidoll.bsky.social/post/3jvbaqkqbo622

**Comment by kawarimidoll** [comment]
Thank you, it fixed 👍 
Nice work!
