### ISSUE TITLE
Discord embedded photos are very small

### ISSUE THREAD

**Issue by infinitejess** [capjamesg/bsky.link#20]
Hello, and thanks for the project!

I'm on a Discord that's using bsky.link to share with the uninvited masses, and the embeds look like this:

![A bsky.link to a post by Low Quality Facts. The thumbnail is to the right of the post text and is very small](https://github.com/capjamesg/bsky.link/assets/317879/1ce57613-9b3a-4c55-b34c-fae6ba43986e)

![A bsky.link to a post by Amy with no text. The thumbnail is to the right of the title and also very small](https://github.com/capjamesg/bsky.link/assets/317879/805258a4-6ec8-490b-9fdd-2b9bf4d61046)

For comparison, here's a psky embed with the desired behavior:

![A psky.app link where the name, text, and image are on three separate paragraphs](https://github.com/capjamesg/bsky.link/assets/317879/b1845eb6-0a65-49e5-932a-a96d2e9e11ba)

I don't know anything about how embeds work, but I might come back with a pull request if I find the time.

**Comment by capjamesg** [comment]
Let me take a look! We are probably missing a bit of metadata. Feel free to file a PR if you would like, too!

**Comment by infinitejess** [comment]
Ah, I see. Per [a stackoverflow answer](https://stackoverflow.com/a/72493123), discord requires twitter metadata. Per my own experimentation the only needed addition is:

    <meta name="twitter:card" content="summary_large_image">

**Comment by capjamesg** [comment]
Feel free to file a PR if you would like!
