### ISSUE TITLE
Photos don't show in threads

### ISSUE THREAD

**Issue by kevinmarks** [capjamesg/bsky.link#6]
eg https://bsky.link/?show_thread=t&url=https://staging.bsky.app/profile/mikamckinnon.bsky.social/post/3jvebdce5cu2i

**Comment by kevinmarks** [comment]
fixed by https://github.com/capjamesg/bsky.link/pull/8

**Comment by capjamesg** [comment]
I'm closing this issue as #8 has been deployed.
